version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelscraping-revise-db
    ports:
      - "81:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel-network
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8

  db:
    image: mysql:8.0
    container_name: laravelscraping-revise-db 
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravelscraping-revise-db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root_password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  mysql-data: